name: stoxhero
description: A new Flutter project.
# version: 1.0.0+80 # Dev
version: 1.0.0+55 # Prod
publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  phonepe_payment_sdk: ^1.0.2
  get: ^4.6.5
  dio: ^5.1.1
  get_storage: ^2.1.1
  intl: ^0.18.1
  package_info_plus: ^3.1.2
  pinput: ^3.0.1
  pretty_dio_logger: ^1.3.1
  fl_chart: ^0.63.0
  socket_io_client: ^2.0.2
  uuid: ^3.0.7
  share_plus: ^7.1.0
  qr_flutter: ^4.0.0
  image_picker: ^1.0.2
  carousel_slider: ^4.2.1
  dropdown_button2: ^2.3.9
  youtube_player_flutter: ^8.1.2
  number_paginator: ^0.3.2
  dotted_border: ^2.1.0
  file_picker: ^5.3.1
  http_parser: ^4.0.2
  mime: ^1.0.4
  flutter_inappwebview: ^5.8.0
  crypto: ^3.0.3
  http: ^0.13.6
  firebase_core: ^2.17.0
  firebase_messaging: ^14.7.4
  firebase_analytics: ^10.5.1
  in_app_update: ^4.2.2
  url_launcher: ^6.1.14
  uni_links: ^0.5.1
  shimmer: ^3.0.0
  logger: ^2.0.2+1
  path_provider: ^2.1.1
  open_filex: ^4.3.4
  flutter_local_notifications: ^16.1.0
  device_info_plus: ^9.1.1
  firebase_dynamic_links: ^5.4.6
  pie_chart: ^5.4.0
  percent_indicator: ^4.2.3
  flutter_animate: ^4.3.0
  animated_text_kit: ^4.2.1
  audioplayers: ^5.2.1
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_launcher_icons: any
  change_app_package_name: ^1.1.0
  flutter_slidable: ^3.0.1
 

flutter_launcher_icons:
  ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#FFFFFF"
  image_path: "assets/icons/app_icon.png"
  image_path_ios: "assets/icons/app_icon.png"
  adaptive_icon_foreground: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/audio/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
